# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.07.1
    ports:
      # DNS Ports
      - "${TAILSCALE_IP}:53:53/tcp"
      - "${TAILSCALE_IP}:53:53/udp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'America/Sao_Paulo'
      FTLCONF_webserver_api_password: "${PIHOLE_WEBPASSWORD}"
      VIRTUAL_HOST: 'hole.homelab'
      WEB_VIRTUAL_HOST: 'hole.homelab'
      VIRTUAL_PORT: 80

      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
      PIHOLE_DNS: "${DNS1};${DNS2}"
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - '${PI_HOLE_CONFIG_STORAGE_PATH}:/etc/pihole'

      # For persisting custom DNS configurations
      - '${PI_HOLE_CONFIG_STORAGE_PATH}:/etc/dnsmasq.d'

      # (Optional) For persisting Pi-hole running text logs
      - '${PI_HOLE_LOGS_STORAGE_PATH}:/var/log'
      
      # Custom hosts file for local DNS entries (persists across restarts)
      - '${PI_HOLE_CONFIG_STORAGE_PATH}/custom-hosts:/etc/hosts'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      - SYS_NICE
    restart: unless-stopped
    networks:
      self-hosted:
        ipv4_address: 172.18.0.10
    
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "google.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  self-hosted:
    external: true